version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vue-i18n
    versions:
    - 8.24.1
    - 8.24.2
    - 8.24.3
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: vue-cli-plugin-i18n
    versions:
    - 2.0.0
    - 2.0.1
    - 2.0.2
    - 2.0.3
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.34
